### ISSUE TITLE
telebooth-server issue

### ISSUE THREAD

**Issue by sarasengi** [aksanoble/telebooth#4]
Hello.
Please help to fix this issue.

Ubuntu 20.04.2 LTS
5.4.0-73-generic x86_64
1GB RAM
CPU 1 core

```root@server:~# cd /root/telebooth-server/
root@server:~/telebooth-server# npm start

> bot-server@1.0.0 start /root/telebooth-server
> nodemon index

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. internal/modules/cjs/loader.js:1085:14
Express server is listening on 3000
(node:18078) UnhandledPromiseRejectionWarning: Error: no mutations exist: {"response":{"errors":[{"extensions":{"path":"$","code":"validation-failed"},"message":"no mutations exist"}],"status":200},"request":{"query":"\n  mutation UpsertUser($username: String!, $first_name: String!, $id: Int!, $is_bot: Boolean!) {\n    insert_user(\n      objects: { id: $id, username: $username, first_name: $first_name, is_bot: $is_bot }\n      on_conflict: { constraint: user_pkey, update_columns: username }\n    ) {\n      returning {\n        id\n        is_bot\n        username\n      }\n    }\n  }\n","variables":{"id":0000000000,"is_bot":true,"first_name":"godo_mafia","username":"godomafia_bot"}}}
    at GraphQLClient.<anonymous> (/root/telebooth-server/node_modules/graphql-request/dist/index.js:172:35)
    at step (/root/telebooth-server/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/root/telebooth-server/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/root/telebooth-server/node_modules/graphql-request/dist/index.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18078) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18078) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by aksanoble** [comment]
Hi Sarasangi! 
Have you started the Hasura GraphQL server? 
I'll need more information on your setup.
